# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BysMobileAds_sdk_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Bys-Mobile-Ads-SDK', '~> 0.0.1’

  # Pods for BysMobileAds_sdk_Demo

  target 'BysMobileAds_sdk_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BysMobileAds_sdk_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
